version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - spinta
      - katalogas
  database:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_DB=spinta
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spinta

networks:
  spinta:
    external: true
  katalogas:
    external: true

volumes:
  postgres:
