@startuml
package commands <<Rectangle>> {

    object render {
        +context: Context,
        +request: Request,
        +model: Model,
        +fmt: JsonLines,
        +*,
        +action: Action,
        +params: UrlParams,
        +data,
        +status_code: int = 200,
        +headers: Optional[dict] = None,
    }
}

render *-- Context
render *-- Request
render *-- Model
render *-- JsonLines
render *-- Action
render *-- UrlParams
render *-- Node

@enduml
