env: production
data_path: $BASEDIR
default_auth_client: default

keymaps:
  default:
    type: sqlalchemy
    dsn: sqlite:///$BASEDIR/keymap.db

backends:
  default:
    type: postgresql
    dsn: postgresql://user:pass@host:54321/spinta

  saugykla_test:
    type: postgresql
    dsn: postgresql://user:pass@host:54321/spinta2


manifest: default
manifests:
  default:
    type: csv
    path: $BASEDIR/manifest.csv
    access: open
    backend: default
    keymap: default
    mode: internal
    sync: test
  saugykla_test:
    type: csv
    path: $BASEDIR/manifest_test.csv
    backend: saugykla_test
    keymap: default
    mode: internal

accesslog:
  type: file
  file: /path/to/accesslog.json
