@startuml
Accesslog <|-- FileAccess
Accesslog <|-- PythonAccessLog
ReadTransaction <|-- WriteTransaction
mongo.ReadTransaction <|-- mongo.WriteTransaction
postgresql.ReadTransaction <|-- postgresql.WriteTransaction
Backend <|-- PostgreSQL
Backend <|-- Mongo
Backend <|-- Memory
Backend *-- BackendOrigin
Backend *-- BackendFeatures
ConfigSource <|-- PyDict
PyDict *-- Path
PyDict *-- CliArgs
ConfigSource *-- EnvVars
EnvVars *-- EnvFile
Expr *-- ShortExpr
Expr *-- MethodExpr
Unresolved <|-- Pair
Unresolved <|-- Bind
Bind *-- Negative
Bind *-- Positive
Env <|-- SqlResource
Env <|-- SqlResultBuilder
Env <|-- PrepareFileResource
KeyMap *-- SqlAlchemyKeyMap
Backend *-- ExternalBackend
External <|-- Resource
External <|-- Entity
External <|-- Attribute
ExternalBackend <|-- Csv
ExternalBackend <|-- FrictionlessBackend
ExternalBackend <|-- BackendNotImplemented
ExternalBackend *--  Sql
Env *-- EnumFormula
Env *-- ParamBuilder
Dimension <|-- UriPrefix
Format *-- Ascii
Format *-- formats.csv.Csv
Format *-- Html
Format *-- Json
Format *-- JsonLines
Manifest *-- BackendManifest
Manifest *-- YamlManifest
YamlManifest *-- InlineManifest
YamlManifest *-- InternalManifest
Manifest *-- TabularManifest
TabularManifest *-- CsvManifest
TabularManifest *-- AsciiManifest
TabularManifest *-- XlsxManifest
TabularManifest *-- GsheetsManifest
Env <|-- NameFormatter
DataType *-- PrimaryKey
DataType *-- Date
DataType *-- Time
DataType *-- DateTime
DataType *-- String
DataType *-- Binary
DataType *-- Integer
DataType *-- Number
DataType *-- Boolean
DataType *-- URL
DataType *-- Ref
DataType *-- BackRef
DataType *-- Generic
DataType *-- Array
DataType *-- Object
DataType *-- File
DataType *-- Image
DataType *-- RQL
DataType *-- JSON
Unresolved *-- ForeignProperty
Component *-- Node
Node *-- MetaData
MetaData *-- Namespace
Node <|-- Base
MetaData <|-- Model
Node *-- Property
MetaData *-- Dataset
Node *-- External
Node *-- EnumItem
Component *-- Manifest
MetaData *-- Owner
MetaData *-- Project
Node *-- types.Model
Node *-- Property
@enduml
