@startuml
package load <<Rectangle>> {

    object load {
        +context: Context,
        +backend: PostgreSQL,
        +config: Dict[str, Any],
    }

    object unload_backend {
        +context: Context,
        +backend: PostgreSQL,
    }

}

load *-- Context
load *-- PostgreSQL
unload_backend *-- Context
unload_backend *-- PostgreSQL
@enduml

