@startuml
package migrate <<Rectangle>> {

    object migrate {
        +context: Context,
        +backend: PostgreSQL,
        +manifest: Manifest,
    }
}

migrate *-- Context
migrate *-- PostgreSQL
migrate *-- Manifest
@enduml

