@startuml
package bootstrap <<Rectangle>> {

    object bootstrap {
        +context: Context
        +manifest: BackendManifest
    }
}

bootstrap *-- Context
bootstrap *-- BackendManifest


@enduml
