@startuml
package migrate <<Rectangle>> {

    object migrate {
        +context: Context,
        +manifest: Manifest,
        +config: Dict[str, Any],

    }
}

migrate *-- Context
migrate *-- Manifest
@enduml
