@startuml
package bootstrap <<Rectangle>> {

    object bootstrap {
        +context: Context,
        +manifest: TabularManifest,

    }
}

bootstrap *-- Context
bootstrap *-- TabularManifest
@enduml
